"""adds security price

Revision ID: 23ee869ccec1
Revises: f98564f5f4c7
Create Date: 2021-09-16 07:08:20.160645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23ee869ccec1'
down_revision = 'f98564f5f4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=8), nullable=False),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('u_high', sa.Float(), nullable=True),
    sa.Column('u_low', sa.Float(), nullable=True),
    sa.Column('u_open', sa.Float(), nullable=True),
    sa.Column('u_close', sa.Float(), nullable=True),
    sa.Column('u_volume', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('change_over_time', sa.Float(), nullable=True),
    sa.Column('market_change_over_time', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_prices')
    # ### end Alembic commands ###
