"""add demo flag to profile

Revision ID: 4debdd6f0f8b
Revises: 4c2c226093a3
Create Date: 2021-09-22 15:03:55.759430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4debdd6f0f8b'
down_revision = '4c2c226093a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('is_demo_profile', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'is_demo_profile')
    # ### end Alembic commands ###
