"""adds profiles

Revision ID: b04087732e10
Revises: b1fae9fa8231
Create Date: 2021-08-26 22:59:44.615454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04087732e10'
down_revision = 'b1fae9fa8231'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('force_password_reset', sa.Boolean(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'accounts', 'profiles', ['profile_id'], ['id'])
    op.add_column('plaid_items', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'plaid_items', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plaid_items', type_='foreignkey')
    op.drop_column('plaid_items', 'profile_id')
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'profile_id')
    op.drop_table('profiles')
    # ### end Alembic commands ###
