"""adds scheduled jobs

Revision ID: e963cefb718f
Revises: 755e669e77dd
Create Date: 2021-09-13 16:17:16.439658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e963cefb718f'
down_revision = '755e669e77dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency_type', sa.String(length=64), nullable=False),
    sa.Column('frequency_value', sa.String(length=32), nullable=False),
    sa.Column('job_name', sa.String(length=128), nullable=False),
    sa.Column('json_args', sa.String(length=2048), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_jobs')
    # ### end Alembic commands ###
