"""remove security_id from security_prices

Revision ID: f09eb0ba1c57
Revises: a98d39f4222c
Create Date: 2021-09-20 10:33:12.185179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f09eb0ba1c57'
down_revision = 'a98d39f4222c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('security_prices_ibfk_1', 'security_prices', type_='foreignkey')
    op.drop_column('security_prices', 'security_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_prices', sa.Column('security_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('security_prices_ibfk_1', 'security_prices', 'securities', ['security_id'], ['id'])
    # ### end Alembic commands ###
