"""fixes bad col name

Revision ID: f98564f5f4c7
Revises: 4ab229f4630a
Create Date: 2021-09-15 12:55:13.323192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f98564f5f4c7'
down_revision = '4ab229f4630a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('account_id', sa.Integer(), nullable=False))
    op.drop_constraint('balances_ibfk_1', 'balances', type_='foreignkey')
    op.create_foreign_key(None, 'balances', 'accounts', ['account_id'], ['id'])
    op.drop_column('balances', 'accountId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('accountId', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'balances', type_='foreignkey')
    op.create_foreign_key('balances_ibfk_1', 'balances', 'accounts', ['accountId'], ['id'])
    op.drop_column('balances', 'account_id')
    # ### end Alembic commands ###
