image: docker:19.03.12

variables:
  DOCKER_TLS_CERTDIR: "/certs"
  CONTAINER_TEST_IMAGE: git.gittos.net/money-printer/money-printer-server:$CI_COMMIT_SHORT_SHA
  CONTAINER_RELEASE_IMAGE: git.gittos.net/money-printer/money-printer-server:latest

services:
  - docker:19.03.12-dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - build
  - test
  - release
  - deploy-staging
  - deploy-production

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
  
test:
  stage: test
  script:
    - docker pull -t $CONTAINER_TEST_IMAGE
    - npm run start
    - npm run test
    - npm run down
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual

release:
  stage: release
  script:
    - docker pull -t $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master
  rules:
    - when: manual
