image: docker:19.03.12

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:19.03.12-dind

before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
  
test:
  stage: test
  script:
    - docker pull -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - npm run start
    - npm run test
    - npm run down
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - when: manual
