variables:
  MYSQL_DATABASE: "mp-test"
  MYSQL_ROOT_PASSWORD: "test root password"
  MYSQL_USER: "moneyprinter"
  MYSQL_PASSWORD: "mp!QAZxsw2"
  MYSQL_HOST: mysql


default:
  image: tgittos/money-printer:latest

stages:
#  - build
  - test

unit-test-job:
  stage: test
  services:
    - mysql:5.7
  script:
    - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
    - mysql --version
    - mysql --user=$MYSQL_USER --password=$MYSQL_PASSWORD --database=$MYSQL_DATABASE --host=$MYSQL_HOST --execute="SHOW DATABASES; ALTER USER '$MYSQL_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$MYSQL_PASSWORD'"
    - echo "installing pip dependencies"
    - pip install -r ./src/requirements.txt
    - echo "pip install complete"
    - echo "running pytest on ./src/tests"
    - MP_ENVIRONMENT=test PYTHONPATH="$PYTHONPATH:./src" pytest ./src/tests

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."