services:
  ngrok:
    image: "wernight/ngrok"
    ports:
      - 4040:4040
    env_file:
      - .env.dev
    environment:
      - NGROK_HEADER="rewrite"
      - NGROK_SUBDOMAIN=tgmp
      - NGROK_PORT=api
      - NGROK_DEBUG=true
  redis:
    image: "redis:alpine"
  matomo:
    image: "git.gittos.net:5050/money-printer/money-printer-infrastructure/mp-matom\
      o:latest"
    ports:
      - 8080:8080
    volumes:
      - matomo-config:/var/www/matomo/config
    env_file:
      - .env.dev
    depends_on: [ "db" ]
  prometheus:
    image: "git.gittos.net:5050/money-printer/money-printer-infrastructure/mp-prome\
      theus:latest"
    ports:
      - 9090:9090
    entrypoint: [ "/bin/sh", "prometheus.sh" ]
  db:
    image: "mysql/mysql-server:5.7"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev-root-password
    ports:
      - 3306:3306
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./docs:/app/docs
      - ./src:/app/src
    ports:
      - 80:80
      - 443:443
    environment:
      MP_REDIS__HOST: redis
      MP_DB__HOST: db
      MP_WEBHOOK_HOST: ngrok
    env_file:
      - .env.dev
    depends_on: [ "redis", "db", "ngrok", "matomo", "prometheus" ]
    image: "git.gittos.net:5050/money-printer/money-printer-server/mp-api"
    entrypoint:
      [
        "python",
        "bin/api-server.py",
        "&&",
        "tail",
        "-f",
        "logs/mp.log"
      ]
  data-server:
    image: mp-api
    environment:
      MP_REDIS__HOST: redis
      MP_DB__HOST: db
    env_file:
      - .env.dev
    depends_on: [ "redis", "db" ]
    entrypoint:
      [
        "python",
        "bin/data-server.py",
        "&&",
        "tail",
        "-f",
        "logs/mp.log"
      ]
  task-runner:
    image: mp-api
    environment:
      MP_REDIS__HOST: redis
      MP_DB__HOST: db
    env_file:
      - .env.dev
    depends_on: [ "redis", "db" ]
    entrypoint: [ "python", "bin/task-runner.py" ]
  scheduler:
    image: mp-api
    environment:
      MP_REDIS__HOST: "redis"
      MP_DB__HOST: db
    env_file:
      - .env.dev
    depends_on: [ "redis", "db" ]
    entrypoint:
      [
        "rqscheduler",
        "--host",
        redis,
        "--port",
        "6379",
        "--db",
        "0"
      ]

volumes:
  db-data: null
  matomo-config: null
