services:
  redis:
    image: "redis:alpine"
  matomo:
    image: "mp-matomo"
    ports:
      - 8080:8080
    env_file:
      - .env.prod
    depends_on: [ "db" ]
  prometheus:
    image: "mp-prometheus"
    ports:
      - 9090:9090
    entrypoint: [ "/bin/sh", "prometheus.sh" ]
  api:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 80:80
      - 443:443
    environment:
      MP_REDIS__HOST: redis
    env_file:
      - .env.prod
    depends_on: [ "redis", "matomo", "prometheus" ]
    image: api
    entrypoint:
      [
        "python",
        "bin/api-server.py",
        "&&",
        "tail",
        "-f",
        "logs/mp.log"
      ]
  data-server:
    image: api
    environment:
      MP_REDIS__HOST: redis
    env_file:
      - .env.prod
    depends_on: [ "redis" ]
    entrypoint:
      [
        "python",
        "bin/data-server.py",
        "&&",
        "tail",
        "-f",
        "logs/mp.log"
      ]
  task-runner:
    image: api
    environment:
      MP_REDIS__HOST: redis
    env_file:
      - .env.prod
    depends_on: [ "redis" ]
    entrypoint: [ "python", "bin/task-runner.py" ]
  scheduler:
    image: api
    environment:
      MP_REDIS__HOST: "redis"
    env_file:
      - .env.prod
    depends_on: [ "redis" ]
    entrypoint:
      [
        "rqscheduler",
        "--host",
        redis,
        "--port",
        "6379",
        "--db",
        "0"
      ]
