services:
  redis:
    image: "redis:alpine"
  matomo:
    image: "mp-matomo"
    ports:
      - 8080:8080
    volumes:
      - matomo-config:/var/www/matomo/config
    env_file:
      - .env.dev
    depends_on: [ "db" ]
  prometheus:
    image: "mp-prometheus"
    ports:
      - 9090:9090
    entrypoint: [ "/bin/sh", "prometheus.sh" ]
  db:
    image: "mysql/mysql-server:5.7"
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: dev-root-password
    ports:
      - 3306:3306
  api:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - .:/app
    ports:
      - 80:80
      - 443:443
    environment:
      MP_REDIS__HOST: redis
      MP_DB__HOST: db
    env_file:
      - .env.dev
    depends_on: [ "redis", "db", "matomo", "prometheus" ]
    image: api
    entrypoint:
      [
        "python",
        "bin/api-server.py",
        "&&",
        "tail",
        "-f",
        "logs/mp.log"
      ]
  data-server:
    image: api
    environment:
      MP_REDIS__HOST: redis
      MP_DB__HOST: db
    env_file:
      - .env.dev
    depends_on: [ "redis", "db" ]
    entrypoint:
      [
        "python",
        "bin/data-server.py",
        "&&",
        "tail",
        "-f",
        "logs/mp.log"
      ]
  task-runner:
    image: api
    environment:
      MP_REDIS__HOST: redis
      MP_DB__HOST: db
    env_file:
      - .env.dev
    depends_on: [ "redis", "db" ]
    entrypoint: [ "python", "bin/task-runner.py" ]
  scheduler:
    image: api
    environment:
      MP_REDIS__HOST: "redis"
      MP_DB__HOST: db
    env_file:
      - .env.dev
    depends_on: [ "redis", "db" ]
    entrypoint:
      [
        "rqscheduler",
        "--host",
        redis,
        "--port",
        "6379",
        "--db",
        "0"
      ]

volumes:
  db-data: null
  matomo-config: null
