"""empty message

Revision ID: e446de893521
Revises: 
Create Date: 2022-01-08 19:02:38.115322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e446de893521'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('iex_blacklists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=265), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('securities',
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('iso_currency_code', sa.String(length=8), nullable=True),
    sa.Column('institution_id', sa.String(length=128), nullable=True),
    sa.Column('institution_security_id', sa.String(length=128), nullable=True),
    sa.Column('security_id', sa.String(length=128), nullable=True),
    sa.Column('proxy_security_id', sa.String(length=128), nullable=True),
    sa.Column('cusip', sa.String(length=16), nullable=True),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('sedol', sa.String(length=16), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.create_table('security_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('u_high', sa.Float(), nullable=True),
    sa.Column('u_low', sa.Float(), nullable=True),
    sa.Column('u_open', sa.Float(), nullable=True),
    sa.Column('u_close', sa.Float(), nullable=True),
    sa.Column('u_volume', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('change_over_time', sa.Float(), nullable=True),
    sa.Column('market_change_over_time', sa.Float(), nullable=True),
    sa.Column('resolution', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['securities.symbol'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('security_prices')
    op.drop_table('securities')
    op.drop_table('iex_blacklists')
    # ### end Alembic commands ###
