services:
  redis:
    image: "redis:alpine"
  db:
    image: "mysql/mysql-server:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: dev-root-password
    ports:
      - 3306:3306
  api:
    build:
      dockerfile: ./../infrastructure/docker/app/Dockerfile.api
      context: ../../src
    ports:
      - 80:80
      - 443:443
    environment:
      MP_REDIS__HOST: redis
      MP_DB__HOST: db
    depends_on: ["redis", "db"]
  data-server:
    build:
      dockerfile: ../infrastructure/docker/app/Dockerfile.data_server
      context: ../../src
    environment:
      MP_REDIS__HOST: redis
      MP_DB__HOST: db
    depends_on: ["redis", "db"]
  task-runner:
    build:
      dockerfile: ../infrastructure/docker/app/Dockerfile.task_runner
      context: ../../src
    environment:
      MP_REDIS__HOST: redis
      MP_DB__HOST: db
    depends_on: ["redis", "db"]
  scheduler:
    build:
      dockerfile: ../infrastructure/docker/app/Dockerfile.scheduler
      context: ../../src
    environment:
      MP_REDIS__HOST: "redis"
      MP_DB__HOST: db
    depends_on: ["redis", "db"]
    image: mp_scheduler
  platform:
    build:
      dockerfile: ../infrastructure/docker/app/base/Dockerfile.server
      context: ../../src
    profiles: ["platform"]