services:
  db:
    image: "mysql/mysql-server:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: test-root-password
    ports:
      - 3306:3306
  api:
    build:
      dockerfile: ./../infrastructure/docker/app/Dockerfile.api
      context: ../../src
    ports:
      - 80:80
      - 443:443
    environment:
      MP_DB__HOST: db
    depends_on: ["db"]