"""Add more associations

Revision ID: 6371d4db33e0
Revises: 6c47ba61bf05
Create Date: 2021-12-21 22:48:29.062862

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6371d4db33e0'
down_revision = '6c47ba61bf05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_results', sa.Column('job_id', sa.String(length=128), nullable=False))
    op.create_foreign_key(None, 'job_results', 'scheduled_jobs', ['scheduled_job_id'], ['id'])
    op.drop_constraint('securities_ibfk_2', 'securities', type_='foreignkey')
    op.drop_constraint('securities_ibfk_1', 'securities', type_='foreignkey')
    op.drop_column('securities', 'profile_id')
    op.drop_column('securities', 'account_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('securities', sa.Column('account_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('securities', sa.Column('profile_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_foreign_key('securities_ibfk_1', 'securities', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('securities_ibfk_2', 'securities', 'profiles', ['profile_id'], ['id'])
    op.drop_constraint(None, 'job_results', type_='foreignkey')
    op.drop_column('job_results', 'job_id')
    # ### end Alembic commands ###
