"""add type to accounts

Revision ID: a90999afd343
Revises: e963cefb718f
Create Date: 2021-09-14 07:17:52.008237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a90999afd343'
down_revision = 'e963cefb718f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('type', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'type')
    # ### end Alembic commands ###
