services:
  redis:
    image: "redis:alpine"
  client:
    build:
      context: client/
    ports:
      - 3000:3000
      - 6060:6060
    environment:
      CHOKIDAR_USEPOLLING: "true"
      HOST: "0.0.0.0"
      MP_API_HOST: "api"
    volumes:
      - ./client:/home/node/app
    stdin_open: true
  api:
    build:
      dockerfile: server/services/api/Dockerfile
      context: .
    ports:
      - 80:80
      - 443:443
    environment:
      MP_ENVIRONMENT: "development"
      MP_HOST: "0.0.0.0"
      MP_REDIS__HOST: "redis"
    depends_on:
      - redis
    volumes:
      - ./:/app
    image: mp_api
  data-server:
    build:
      dockerfile: server/services/data_server/Dockerfile
      context: .
    environment:
      MP_ENVIRONMENT: "development"
      MP_HOST: "0.0.0.0"
      MP_REDIS__HOST: "redis"
    depends_on:
      - redis
    volumes:
      - ./:/app
    image: mp_data
  task-runner:
    build:
      dockerfile: server/services/task_runner/Dockerfile
      context: .
    environment:
      MP_ENVIRONMENT: "development"
      MP_HOST: "0.0.0.0"
      MP_REDIS__HOST: "redis"
    depends_on:
      - redis
    volumes:
      - ./:/app
    image: mp_runner
  scheduler:
    build:
      dockerfile: server/services/scheduler/Dockerfile
      context: .
    environment:
      MP_REDIS__HOST: "redis"
    depends_on:
      - redis
    image: mp_scheduler

