version: '3.8'

services:
  redis:
    image: "redis:alpine"
  api:
    environment:
      MP_ENVIRONMENT: "development"
      MP_HOST: "0.0.0.0"
      MP_REDIS__HOST: "redis"
    build:
      context: .
      dockerfile: server/services/api/Dockerfile
    ports:
      - "8000:8000"
    links:
      - redis
    depends_on: [redis]
    image: mp_api
  data_server:
    environment:
      MP_ENVIRONMENT: "development"
      MP_REDIS__HOST: "redis"
    build:
      context: .
      dockerfile: server/services/data_server/Dockerfile
    links:
      - redis
    depends_on: [redis]
    image: data_server
  task_runner:
    environment:
      MP_ENVIRONMENT: "development"
      MP_REDIS__HOST: "redis"
    build:
      context: .
      dockerfile: server/services/task_runner/Dockerfile
    links:
      - redis
    depends_on: [redis]
    image: task_runner
