version: '3.8'

services:
  redis:
    image: "redis:alpine"
  api:
    environment:
      MP_ENVIRONMENT: "development"
      MP_REDIS__HOST: "redis://redis"
    build: ./server/services/api
    command: ./server/bin/api
    volumes:
      - . /usr/app
    ports:
      - "5000:5000"
    depends_on: redis
  client_bus:
    environment:
      MP_ENVIRONMENT: "development"
      MP_REDIS__HOST: "redis://redis"
    build: ./server/services/client_bus
    command: ./server/bin/client_bus
    volumes:
      - . /usr/app
    ports:
      - "8000:8000"
      - "8443:8443"
    depends_on: redis
  data_server:
    environment:
      MP_ENVIRONMENT: "development"
      MP_REDIS__HOST: "redis://redis"
    build: ./server/services/data_services
    command: ./server/bin/data_services
    volumes:
      - . /usr/app
    depends_on: redis
  task_runner:
    environment:
      MP_ENVIRONMENT: "development"
      MP_REDIS__HOST: "redis://redis"
    build: ./server/services/task_runner
    command: ./server/bin/task_runner
    volumes:
      - . /usr/app
    depends_on: redis
